// Generated by gencpp from file talkersrv/contrl.msg
// DO NOT EDIT!


#ifndef TALKERSRV_MESSAGE_CONTRL_H
#define TALKERSRV_MESSAGE_CONTRL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mavros_msgs/PositionTarget.h>

namespace talkersrv
{
template <class ContainerAllocator>
struct contrl_
{
  typedef contrl_<ContainerAllocator> Type;

  contrl_()
    : flag(0)
    , mode(0)
    , number(0)
    , pose()  {
    }
  contrl_(const ContainerAllocator& _alloc)
    : flag(0)
    , mode(0)
    , number(0)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _flag_type;
  _flag_type flag;

   typedef uint8_t _mode_type;
  _mode_type mode;

   typedef int32_t _number_type;
  _number_type number;

   typedef  ::mavros_msgs::PositionTarget_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::talkersrv::contrl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::talkersrv::contrl_<ContainerAllocator> const> ConstPtr;

}; // struct contrl_

typedef ::talkersrv::contrl_<std::allocator<void> > contrl;

typedef boost::shared_ptr< ::talkersrv::contrl > contrlPtr;
typedef boost::shared_ptr< ::talkersrv::contrl const> contrlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::talkersrv::contrl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::talkersrv::contrl_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::talkersrv::contrl_<ContainerAllocator1> & lhs, const ::talkersrv::contrl_<ContainerAllocator2> & rhs)
{
  return lhs.flag == rhs.flag &&
    lhs.mode == rhs.mode &&
    lhs.number == rhs.number &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::talkersrv::contrl_<ContainerAllocator1> & lhs, const ::talkersrv::contrl_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace talkersrv

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::talkersrv::contrl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::talkersrv::contrl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::talkersrv::contrl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::talkersrv::contrl_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::talkersrv::contrl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::talkersrv::contrl_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::talkersrv::contrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "86c139ad945932fc6cc8e0987ddcb569";
  }

  static const char* value(const ::talkersrv::contrl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x86c139ad945932fcULL;
  static const uint64_t static_value2 = 0x6cc8e0987ddcb569ULL;
};

template<class ContainerAllocator>
struct DataType< ::talkersrv::contrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "talkersrv/contrl";
  }

  static const char* value(const ::talkersrv::contrl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::talkersrv::contrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 flag\n"
"uint8 mode\n"
"int32 number\n"
"mavros_msgs/PositionTarget pose\n"
"================================================================================\n"
"MSG: mavros_msgs/PositionTarget\n"
"# Message for SET_POSITION_TARGET_LOCAL_NED\n"
"#\n"
"# Some complex system requires all feautures that mavlink\n"
"# message provide. See issue #402.\n"
"\n"
"std_msgs/Header header\n"
"\n"
"uint8 coordinate_frame\n"
"uint8 FRAME_LOCAL_NED = 1\n"
"uint8 FRAME_LOCAL_OFFSET_NED = 7\n"
"uint8 FRAME_BODY_NED = 8\n"
"uint8 FRAME_BODY_OFFSET_NED = 9\n"
"\n"
"uint16 type_mask\n"
"uint16 IGNORE_PX = 1	# Position ignore flags\n"
"uint16 IGNORE_PY = 2\n"
"uint16 IGNORE_PZ = 4\n"
"uint16 IGNORE_VX = 8	# Velocity vector ignore flags\n"
"uint16 IGNORE_VY = 16\n"
"uint16 IGNORE_VZ = 32\n"
"uint16 IGNORE_AFX = 64	# Acceleration/Force vector ignore flags\n"
"uint16 IGNORE_AFY = 128\n"
"uint16 IGNORE_AFZ = 256\n"
"uint16 FORCE = 512	# Force in af vector flag\n"
"uint16 IGNORE_YAW = 1024\n"
"uint16 IGNORE_YAW_RATE = 2048\n"
"\n"
"geometry_msgs/Point position\n"
"geometry_msgs/Vector3 velocity\n"
"geometry_msgs/Vector3 acceleration_or_force\n"
"float32 yaw\n"
"float32 yaw_rate\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::talkersrv::contrl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::talkersrv::contrl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.flag);
      stream.next(m.mode);
      stream.next(m.number);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct contrl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::talkersrv::contrl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::talkersrv::contrl_<ContainerAllocator>& v)
  {
    s << indent << "flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.flag);
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
    s << indent << "number: ";
    Printer<int32_t>::stream(s, indent + "  ", v.number);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::mavros_msgs::PositionTarget_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TALKERSRV_MESSAGE_CONTRL_H
