# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from talkersrv/contrl.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import mavros_msgs.msg
import std_msgs.msg

class contrl(genpy.Message):
  _md5sum = "86c139ad945932fc6cc8e0987ddcb569"
  _type = "talkersrv/contrl"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 flag
uint8 mode
int32 number
mavros_msgs/PositionTarget pose
================================================================================
MSG: mavros_msgs/PositionTarget
# Message for SET_POSITION_TARGET_LOCAL_NED
#
# Some complex system requires all feautures that mavlink
# message provide. See issue #402.

std_msgs/Header header

uint8 coordinate_frame
uint8 FRAME_LOCAL_NED = 1
uint8 FRAME_LOCAL_OFFSET_NED = 7
uint8 FRAME_BODY_NED = 8
uint8 FRAME_BODY_OFFSET_NED = 9

uint16 type_mask
uint16 IGNORE_PX = 1	# Position ignore flags
uint16 IGNORE_PY = 2
uint16 IGNORE_PZ = 4
uint16 IGNORE_VX = 8	# Velocity vector ignore flags
uint16 IGNORE_VY = 16
uint16 IGNORE_VZ = 32
uint16 IGNORE_AFX = 64	# Acceleration/Force vector ignore flags
uint16 IGNORE_AFY = 128
uint16 IGNORE_AFZ = 256
uint16 FORCE = 512	# Force in af vector flag
uint16 IGNORE_YAW = 1024
uint16 IGNORE_YAW_RATE = 2048

geometry_msgs/Point position
geometry_msgs/Vector3 velocity
geometry_msgs/Vector3 acceleration_or_force
float32 yaw
float32 yaw_rate

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['flag','mode','number','pose']
  _slot_types = ['uint8','uint8','int32','mavros_msgs/PositionTarget']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       flag,mode,number,pose

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(contrl, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.flag is None:
        self.flag = 0
      if self.mode is None:
        self.mode = 0
      if self.number is None:
        self.number = 0
      if self.pose is None:
        self.pose = mavros_msgs.msg.PositionTarget()
    else:
      self.flag = 0
      self.mode = 0
      self.number = 0
      self.pose = mavros_msgs.msg.PositionTarget()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2Bi3I().pack(_x.flag, _x.mode, _x.number, _x.pose.header.seq, _x.pose.header.stamp.secs, _x.pose.header.stamp.nsecs))
      _x = self.pose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_BH9d2f().pack(_x.pose.coordinate_frame, _x.pose.type_mask, _x.pose.position.x, _x.pose.position.y, _x.pose.position.z, _x.pose.velocity.x, _x.pose.velocity.y, _x.pose.velocity.z, _x.pose.acceleration_or_force.x, _x.pose.acceleration_or_force.y, _x.pose.acceleration_or_force.z, _x.pose.yaw, _x.pose.yaw_rate))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pose is None:
        self.pose = mavros_msgs.msg.PositionTarget()
      end = 0
      _x = self
      start = end
      end += 18
      (_x.flag, _x.mode, _x.number, _x.pose.header.seq, _x.pose.header.stamp.secs, _x.pose.header.stamp.nsecs,) = _get_struct_2Bi3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pose.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.pose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 83
      (_x.pose.coordinate_frame, _x.pose.type_mask, _x.pose.position.x, _x.pose.position.y, _x.pose.position.z, _x.pose.velocity.x, _x.pose.velocity.y, _x.pose.velocity.z, _x.pose.acceleration_or_force.x, _x.pose.acceleration_or_force.y, _x.pose.acceleration_or_force.z, _x.pose.yaw, _x.pose.yaw_rate,) = _get_struct_BH9d2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2Bi3I().pack(_x.flag, _x.mode, _x.number, _x.pose.header.seq, _x.pose.header.stamp.secs, _x.pose.header.stamp.nsecs))
      _x = self.pose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_BH9d2f().pack(_x.pose.coordinate_frame, _x.pose.type_mask, _x.pose.position.x, _x.pose.position.y, _x.pose.position.z, _x.pose.velocity.x, _x.pose.velocity.y, _x.pose.velocity.z, _x.pose.acceleration_or_force.x, _x.pose.acceleration_or_force.y, _x.pose.acceleration_or_force.z, _x.pose.yaw, _x.pose.yaw_rate))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pose is None:
        self.pose = mavros_msgs.msg.PositionTarget()
      end = 0
      _x = self
      start = end
      end += 18
      (_x.flag, _x.mode, _x.number, _x.pose.header.seq, _x.pose.header.stamp.secs, _x.pose.header.stamp.nsecs,) = _get_struct_2Bi3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pose.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.pose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 83
      (_x.pose.coordinate_frame, _x.pose.type_mask, _x.pose.position.x, _x.pose.position.y, _x.pose.position.z, _x.pose.velocity.x, _x.pose.velocity.y, _x.pose.velocity.z, _x.pose.acceleration_or_force.x, _x.pose.acceleration_or_force.y, _x.pose.acceleration_or_force.z, _x.pose.yaw, _x.pose.yaw_rate,) = _get_struct_BH9d2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2Bi3I = None
def _get_struct_2Bi3I():
    global _struct_2Bi3I
    if _struct_2Bi3I is None:
        _struct_2Bi3I = struct.Struct("<2Bi3I")
    return _struct_2Bi3I
_struct_BH9d2f = None
def _get_struct_BH9d2f():
    global _struct_BH9d2f
    if _struct_BH9d2f is None:
        _struct_BH9d2f = struct.Struct("<BH9d2f")
    return _struct_BH9d2f
